// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpyxn1mzETvC9ijxV4WsivzL77q17J6o',
    appId: '1:558508613379:web:88b8ba228a5d5e208c9336',
    messagingSenderId: '558508613379',
    projectId: 'flutter-shopping-list-ab54b',
    authDomain: 'flutter-shopping-list-ab54b.firebaseapp.com',
    databaseURL: 'https://flutter-shopping-list-ab54b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shopping-list-ab54b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7_R9eGnvhrufvAJnW3LSX18WwHzJS4vE',
    appId: '1:558508613379:android:d552bd53b73f1ae68c9336',
    messagingSenderId: '558508613379',
    projectId: 'flutter-shopping-list-ab54b',
    databaseURL: 'https://flutter-shopping-list-ab54b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shopping-list-ab54b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXi2TpCkxmkYrZbjeGRjXrq2y_U88VjMc',
    appId: '1:558508613379:ios:a1c4fbd9d94e402d8c9336',
    messagingSenderId: '558508613379',
    projectId: 'flutter-shopping-list-ab54b',
    databaseURL: 'https://flutter-shopping-list-ab54b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shopping-list-ab54b.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXi2TpCkxmkYrZbjeGRjXrq2y_U88VjMc',
    appId: '1:558508613379:ios:2670201aab92d87b8c9336',
    messagingSenderId: '558508613379',
    projectId: 'flutter-shopping-list-ab54b',
    databaseURL: 'https://flutter-shopping-list-ab54b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shopping-list-ab54b.appspot.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
